<?php
$arr = [
    "Home",
    "About",
    "Services",
    "Blog",
    "Features",
    "Shop",
    "Appointment",
    "Pricing plan",
    "Gallery",
    "FAQ",
    "Team",
    "contact",
    "png",
    "Sponsor By",
    "Profile",
    'Change Password',
    "Sign In",
    "Sign Out",
    "Book Appointment",
    "Copyright",
    "Cart Subtotal",
    "Edit Profile",
    "My Appointment",
    "my wish list",
    "Full Name",
    "Phone Number",
    "Choose service",
    "Type Your Massage",
    "PURCHASE NOW",
    "Email",
    "Email address",
    "Password",
    "Remember me",
    "Forgot password",
    "sign in",
    "Register",
    "First Name",
    "Last Name",
    "Username",
    "country",
    "Your Phone Number",
    "Confirm Password",
    "Already have an account",
    "cart",
    "checkout",
    "About us",
    "Contact",
    "subscribe",
    "English",
    "Spanish",
    "Swedish",
    "Turkish",
    "My Account",
    "Read more",
    "Per",
    "team-member",
    "Orders",
    "Plans",
    "Favourites",
    "Order Number",
    "Product",
    "Price",
    "Qty",
    "status",
    "Pending",
    "Processing",
    "On Shipping",
    "Ship",
    "Completed",
    "Cancel",
    "Refund",
    "Return",
    "No Plan Purchase",
    "Added At",
    "Action",
    "No Post Available",
    "Back",
    "search",
    "Categories",
    "Apply now",
    "categories",
    "Phone Number",
    "Current Address",
    "submit",
    "Job Application",
    "Please complete the form below to apply for a position",
    "Availability",
    "Quantity",
    "Total",
    "Attributes",
    "Available",
    "Total Item",
    "Clear Cart",
    "Cart Total",
    "Checkout",
    "Shipping Address",
    "Street Address",
    "Town / City",
    "Postcode",
    "Checkout Summary",
    "Subtotal",
    "Shipping",
    "Payable Total",
    "Cash On Delivery",
    "Choose How Do Want To Pay",
    "Conversation Rate",
    "Percentage  Charge",
    "Fixed Charge",
    "Total Amount",
    "Place Order",
    "Leave a Message",
    "Enter Name",
    "Subject",
    "Write Message",
    "Address",
    "Order No",
    "Order Date",
    "Payment",
    "Thank you. Your order has been received",
    "You order has been confirmed and will be shipped in next few days!",
    "Your order Confirmed",
    "We will be sending shipping confirmation email when the item shipped successfully",
    "Thanks for shopping with us",
    "Order Received",
    "Select Payment Method",
    "Choose How Do You Want To Pay",
    "Pay now",
    "Plan Price",
    "Project Information",
    "Client Name",
    "Service Type",
    "Start Date",
    "End Date",
    "Duration",
    "Status",
    "Add to cart",
    "Description",
    "Reviews",
    "Add A Review",
    "POST REPLY",
    "Description",
    "Submit now",
    "Filter by price",
    "Color",
    "Size",
    "Contact Now",
    "Admin",
    "Search",
    "my favourites",
    "Dashboard",
    "my orders",
    "my plans",
    "my transaction",
    "Account Setting",
    "Transaction Search",
    "Transaction Id",
    "Detail",
    "Purchase Date",
    "Expire Date",
    "Product Name",
    "Buy Now",
    "Shipping Information",
    "Apartment, Street Address",
    "postcode",
    "Your Country",
    "State",
    "Company Name",
    "Hello",
    "Customer Review",
    "ORDER NOW",
    "Comment",
    "Showing All Results",
    "Default Sorting",
    "Latest",
    "Low to High",
    "High to Low",
    "Product doesn't Available",
    "Search Here",
    "READ MORE",
    "Image",
    "Product Name",
    "Price",
    "Attributes",
    "Quantity",
    "Total",
    "Remove",
    "CONTINUE SHOPPING",
    "CLEAR CART",
    "PROCEED CHECKOUT",
    "Sub Total",
    "Pampering you from top to toe with everything your hair, needs!",
    "You have no notifications",
    "Position",
    "Experience",
    "Level",
    "Added Date",
    "Filter",
    "Remark",
    "Date Of Appointment",
    "Appointment Time",
    "Service Name",
    "Upcoming Appointment",
    "I Have Read And Agree To The Website Terms And Conditions",
    "Remember Me",
    "Don't have any account",
    "Haven’t any account",
    "Already have account",

];
return $arr;
